services:
  search-webscraper-markdown:
    image: ghcr.io/lucanori/web2md:rolling
    container_name: search-webscraper-markdown
    ports:
      - "8000:8000"
    depends_on:
      - searxng
      - browserless
    
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw

  browserless:
    container_name: browserless
    image: ghcr.io/browserless/chromium
    restart: unless-stopped
    networks:
      - default
    ports:
      - "3000:3000"
    environment:
      - TOKEN=${BROWSERLESS_TOKEN}
      - MAX_CONCURRENT_SESSIONS=10
      - TIMEOUT=60000
      - QUEUED=10

networks:
  default:
    driver: bridge
